version: "3.9"

services:
  app:
    image: starwiz_ai_django:prod
    container_name: rj_starwiz_ai_django_server
    restart: always
    depends_on:
      - redis
      - nginx
    network_mode: bridge
    volumes:
      - "../:/app/"
      - "/mnt/nas246/public/DataWiz/ais/assets/:/app/assets/"
    ports:
      - "5177:5177"
  redis:
    image: redis:7-alpine
    container_name: rj_starwiz_ai_redis
    network_mode: bridge
    restart: always
    ports:
      - "56379:6379"
    command: [ "redis-server", "/etc/redis.conf", "--appendonly", "yes" ]
    volumes:
      - ../running/redis/data:/data
      - ../running/redis/redis.conf:/etc/redis.conf
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -p 6379 info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  nginx: 
    image: nginx:latest
    container_name: rj_starwiz_ai_django_nginx
    restart: always
    ports:
      - "5178:80"
      - "5179:443"
    volumes:
      - ../build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../build/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../assets:/app/assets
    environment:
      - NGINX_PORT=80
      - TZ=Asia/Shanghai